### ISSUE TITLE
Quais tecnologias serão utilizadas nesta API?

### ISSUE THREAD

**Issue by clebertsilva28** [teresinahc/api-denuncia-de-aglomeracao#2]

**Comment by movibe** [comment]
Eu tenho experiência com hasura.io, ele oferece um ótimo sistema de api em Graphql com Realtime e um ótimo sistema de segurança, além de integração com o Firebase Login, posso estar contribuindo com o projeto também

**Comment by SampaioLeal** [comment]
Opa, por enquanto iniciamos com o bom e velho express, já que serão poucos endpoints e não há a necessidade de autenticação (por enquanto).

Nosso foco estará sendo em armazenar as informações das denúncias (coordenadas, endereço por extenso, horário, etc), e o processamento das imagens que serão enviadas.

Um sistema de detecção de conteúdo impróprio é imprescendível.

**Comment by clebertsilva28** [comment]
> Opa, por enquanto iniciamos com o bom e velho express, já que serão poucos endpoints e não há a necessidade de autenticação (por enquanto).
> 
> Nosso foco estará sendo em armazenar as informações das denúncias (coordenadas, endereço por extenso, horário, etc), e o processamento das imagens que serão enviadas.
> 
> Um sistema de detecção de conteúdo impróprio é imprescendível.

@SampaioLeal, põe no README os requisitos funcionais e não funcionais do projeto, isso deixa tudo mais claro em relação a onde vocês querem chegar e as tecnologias que já estão utilizando. ;)

**Comment by SampaioLeal** [comment]
Entendo. Estou preparando uma descrição mais detalhada, mas foi tudo muito rápido e eu tô morto kkkkk
