### ISSUE TITLE
Criar container com Docker-Compose

### ISSUE THREAD

**Issue by SampaioLeal** [teresinahc/api-denuncia-de-aglomeracao#6]
# Proposta
Será uma ajuda e tanto para novos desenvolvedores se criarmos um container para dar o boot na aplicação, tanto em desenvolvimento quanto em produção, não havendo a necessidade de criar um banco postgres na máquina local.

**Comment by Rickecr** [comment]
Isso seria muito bom.

Eu nunca usei o docker compose. Mas se ninguém mais experiente no assunto aparecer, posso ficar responsável por essa issue :)

**Comment by Rickecr** [comment]
Resolvida em #8 .
